### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dkhodakivskyi** [dirathea/kubectl-unused-volumes#3]
Thanks for the tool. It's really cool job. 

But on some clusters I get the following error:

> $ kubectl unused-volumes 

```panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf90404]

goroutine 1 [running]:
github.com/dirathea/kubectl-unused-volumes/pkg/workload.job.IsEmpty(...)
        /Users/aldiraraharja/ssi-gopath-symlink/src/github.com/dirathea/kubectl-unused-volumes/pkg/workload/workload.go:111
github.com/dirathea/kubectl-unused-volumes/pkg/plugin.RunPlugin(0xc0001b3550, 0xc000408700, 0xc0004496d0, 0xc000139d58, 0x10d99f1)
	/Users/aldiraraharja/ssi-gopath-symlink/src/github.com/dirathea/kubectl-unused-volumes/pkg/plugin/plugin.go:65 +0x32c
github.com/dirathea/kubectl-unused-volumes/cmd/plugin/cli.RootCmd.func2(0xc000285180, 0x1eb2c30, 0x0, 0x0, 0x0, 0x0)
	/Users/aldiraraharja/ssi-gopath-symlink/src/github.com/dirathea/kubectl-unused-volumes/cmd/plugin/cli/root.go:30 +0x31
github.com/spf13/cobra.(*Command).execute(0xc000285180, 0xc00003a1d0, 0x0, 0x0, 0xc000285180, 0xc00003a1d0)
	/Users/aldiraraharja/ssi-gopath-symlink/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:762 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000285180, 0x441d1a, 0x1e02040, 0xc00005c778)
	/Users/aldiraraharja/ssi-gopath-symlink/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/aldiraraharja/ssi-gopath-symlink/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/dirathea/kubectl-unused-volumes/cmd/plugin/cli.InitAndExecute()
	/Users/aldiraraharja/ssi-gopath-symlink/src/github.com/dirathea/kubectl-unused-volumes/cmd/plugin/cli/root.go:50 +0x2b
main.main()
	/Users/aldiraraharja/ssi-gopath-symlink/src/github.com/dirathea/kubectl-unused-volumes/cmd/plugin/main.go:12 +0x20```


I noticed this error occurs with some namespaces where are no any pvc/pv(s) , but job/cronjob exist and a lot pods in status `Completed`

**Comment by dirathea** [comment]
Hi @dkhodakivskyi thanks for the issues, I will look into it.

**Comment by dirathea** [comment]
Hi @dkhodakivskyi, I think the main issue is on the Job Workload filter at https://github.com/dirathea/kubectl-unused-volumes/blob/master/pkg/workload/workload.go#L111, the completions on job spec is optional, so the value might be nil.

**Comment by dkhodakivskyi** [comment]
hi @dirathea . I see. Thanks.

**Comment by dirathea** [comment]
It should be fixed in latest release https://github.com/dirathea/kubectl-unused-volumes/releases/tag/v0.1.2
